# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  python_version: "3.10"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.python_version }}"

      - uses: Gr1N/setup-poetry@v8

      - name: Install Dependencies
        run: |
          poetry --version
          poetry install

      - name: Style format check
        run: |
          poetry run flake8 ./**/*.py

      - name: Static type check
        run: |
          poetry run pyright ./**/*.py

      - name: Build Testing
        run: |
          poetry build

      - name: Unit Test
        run: |
          poetry run pytest
